troubleshooting v4

diff --git a/.github/workflows/ci-cd-aks.yml b/.github/workflows/ci-cd-aks.yml
--- a/.github/workflows/ci-cd-aks.yml
+++ b/.github/workflows/ci-cd-aks.yml
@@ -17,7 +17,17 @@ jobs:
     steps:
       - name: Checkout Code
         uses: actions/checkout@v4
+        with:
+          fetch-depth: 0   # pega todo o histórico, evita problemas com paths
 
+      - name: Debug repo after checkout
+        run: |
+          pwd
+          echo "List root:"
+          ls -l
+          echo "List Kubernetes folder:"
+          ls -l Kubernetes || echo "Kubernetes folder not found"
+        
       - name: Setup .NET 8.0
         uses: actions/setup-dotnet@v3
         with:
@@ -62,7 +72,7 @@ jobs:
         with:
           creds: ${{ secrets.AZURE_CREDENTIALS }}
 
-      - name: Set AKS context
+      - name: Set AKS contextKubernetes/
         run: az aks get-credentials --resource-group RG_FCG --name aks-fcg --overwrite-existing
         
       - name: Debug repo structure
@@ -77,7 +87,7 @@ jobs:
              ls -l Kubernetes || echo "Kubernetes does not exist"
 
       - name: Apply Namespaces
-        run: kubectl apply -f FCG.Users/Kubernetes/namespace.yaml
+        run: kubectl apply -f Kubernetes/namespace.yaml
 
       - name: Deploy to AKS - DEV
         run: |
@@ -89,8 +99,8 @@ jobs:
              export NEW_RELIC_ENDPOINT=${{ vars.NEW_RELIC_ENDPOINT }}
              export ENVIRONMENT=${{ vars.ENV }}
              
-             envsubst < FCG.Users/Kubernetes/deployment.yaml | kubectl apply -n fcg-dev -f -
-             kubectl apply -f FCG.Users/Kubernetes/service.yaml -n fcg-dev
+             envsubst < Kubernetes/deployment.yaml | kubectl apply -n fcg-dev -f -
+             kubectl apply -f Kubernetes/service.yaml -n fcg-dev
              kubectl rollout status deployment/fcg-users -n fcg-dev
 
   deploy-uat:
@@ -110,7 +120,7 @@ jobs:
         run: az aks get-credentials --resource-group RG_FCG --name aks-fcg --overwrite-existing
         
       - name: Apply Namespaces
-        run: kubectl apply -f FCG.Users/Kubernetes/namespace.yaml
+        run: kubectl apply -f Kubernetes/namespace.yaml
 
       - name: Deploy to AKS - UAT
         run: |
@@ -122,8 +132,8 @@ jobs:
              export NEW_RELIC_ENDPOINT=${{ vars.NEW_RELIC_ENDPOINT }}
              export ENVIRONMENT=${{ vars.ENV }}
              
-             envsubst < FCG.Users/Kubernetes/deployment.yaml | kubectl apply -n fcg-uat -f -
-             kubectl apply -f FCG.Users/Kubernetes/service.yaml -n fcg-uat
+             envsubst < Kubernetes/deployment.yaml | kubectl apply -n fcg-uat -f -
+             kubectl apply -f Kubernetes/service.yaml -n fcg-uat
              kubectl rollout status deployment/fcg-users -n fcg-uat
 
   deploy-prd:
@@ -145,7 +155,7 @@ jobs:
         run: az aks get-credentials --resource-group RG_FCG --name aks-fcg --overwrite-existing
         
       - name: Apply Namespaces
-        run: kubectl apply -f FCG.Users/Kubernetes/namespace.yaml
+        run: kubectl apply -f Kubernetes/namespace.yaml
 
       - name: Deploy to AKS - PRD
         run: |
@@ -157,6 +167,6 @@ jobs:
              export NEW_RELIC_ENDPOINT=${{ vars.NEW_RELIC_ENDPOINT }}
              export ENVIRONMENT=${{ vars.ENV }}
              
-             envsubst < FCG.Users/Kubernetes/deployment.yaml | kubectl apply -n fcg -f -
-             kubectl apply -f FCG.Users/Kubernetes/service.yaml -n fcg
+             envsubst < Kubernetes/deployment.yaml | kubectl apply -n fcg -f -
+             kubectl apply -f Kubernetes/service.yaml -n fcg
              kubectl rollout status deployment/fcg-users -n fcg
